//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    using System.IO;
    using System.DirectoryServices;
    using System.Windows.Forms.Design;
    using System.ComponentModel;
    using LimnorDatabase;
    
    public class Form4 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.TextBox TextBox1;
        protected internal LimnorDatabase.EasyGridDetail EasyGridDetail1;
        private System.ComponentModel.IContainer components;
        private static Form4 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form4()
        {
            this.InitializeComponent();
        }
        public static Form4 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form4();
                }
                return _DefaultForm;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form4));
            this.TextBox1 = new System.Windows.Forms.TextBox();
            this.EasyGridDetail1 = new LimnorDatabase.EasyGridDetail();
            this.components = new System.ComponentModel.Container();
            ((System.ComponentModel.ISupportInitialize)(EasyGridDetail1)).BeginInit();
            this.SuspendLayout();
            // 
            // TextBox1
            // 
            this.TextBox1.AutoCompleteCustomSource.AddRange(new string[] {
                        "3-4 70",
                        "8-9 90"});
            this.TextBox1.Location = new System.Drawing.Point(71, 214);
            this.TextBox1.Name = "TextBox1";
            this.TextBox1.Size = new System.Drawing.Size(100, 20);
            this.TextBox1.TabIndex = 0;
            // 
            // EasyGridDetail1
            // 
            this.EasyGridDetail1.AutoGenerateColumns = false;
            this.EasyGridDetail1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.EasyGridDetail1.DataPreparer = null;
            this.EasyGridDetail1.DetailsKeyColumns = null;
            this.EasyGridDetail1.Field_DataSize = new int[0];
            this.EasyGridDetail1.Field_Editor = null;
            this.EasyGridDetail1.Field_Expression = new string[0];
            this.EasyGridDetail1.Field_FieldCaption = new string[0];
            this.EasyGridDetail1.Field_FieldText = new string[0];
            this.EasyGridDetail1.Field_FromTableName = new string[0];
            this.EasyGridDetail1.Field_Indexed = new bool[0];
            this.EasyGridDetail1.Field_Iscalculated = new bool[0];
            this.EasyGridDetail1.Field_IsIdentity = new bool[0];
            this.EasyGridDetail1.Field_Name = new string[0];
            this.EasyGridDetail1.Field_OleDbType = new System.Data.OleDb.OleDbType[0];
            this.EasyGridDetail1.Field_ReadOnly = new bool[0];
            this.EasyGridDetail1.From = null;
            this.EasyGridDetail1.GroupBy = null;
            this.EasyGridDetail1.Having = null;
            this.EasyGridDetail1.Limit = null;
            this.EasyGridDetail1.Location = new System.Drawing.Point(12, 44);
            this.EasyGridDetail1.Master = null;
            this.EasyGridDetail1.MasterKeyColumns = null;
            this.EasyGridDetail1.Name = "EasyGridDetail1";
            this.EasyGridDetail1.OrderBy = null;
            this.EasyGridDetail1.Param_Name = new string[0];
            this.EasyGridDetail1.Param_OleDbType = new System.Data.OleDb.OleDbType[0];
            this.EasyGridDetail1.Param_Value = new string[0];
            this.EasyGridDetail1.RowIndex = -1;
            this.EasyGridDetail1.Size = new System.Drawing.Size(240, 150);
            this.EasyGridDetail1.SqlTop = 0;
            this.EasyGridDetail1.TabIndex = 1;
            this.EasyGridDetail1.TableName = "Table920273386";
            this.EasyGridDetail1.TableToUpdate = null;
            this.EasyGridDetail1.Where = null;
            // 
            // Form4
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(282, 257);
            this.Controls.Add(this.TextBox1);
            this.Controls.Add(this.EasyGridDetail1);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form4";
            this.Text = "Form4";
            EasyGridDetail1.CreateDataTable();
            EasyGridDetail1.Query();
            ((System.ComponentModel.ISupportInitialize)(EasyGridDetail1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        protected override void Dispose(bool disposing)
        {
            if ((disposing 
                        && (components != null)))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
