//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    using Limnor.Net;
    using LimnorDatabase;
    using System.Data.OleDb;
    using System.Data;
    
    public class Form1 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.PictureBox PictureBox1;
        protected internal System.Windows.Forms.Label LabelLNM;
        protected internal System.Windows.Forms.Label LabelFNM;
        protected internal System.Windows.Forms.Label LabelSTATE;
        protected internal System.Windows.Forms.Label LabelCONTACT;
        protected internal System.Windows.Forms.Label LabelEMAIL;
        protected internal System.Windows.Forms.Label LabelLOGIN;
        protected internal System.Windows.Forms.Label LabelPASS;
        protected internal System.Windows.Forms.TextBox TextBoxFNM;
        protected internal System.Windows.Forms.TextBox TextBoxLNM;
        protected internal System.Windows.Forms.TextBox TextBoxSTATE;
        protected internal System.Windows.Forms.TextBox TextBoxCONTACT;
        protected internal System.Windows.Forms.TextBox TextBoxEMAIL;
        protected internal System.Windows.Forms.TextBox TextBoxLOGIN;
        protected internal System.Windows.Forms.TextBox TextBoxPASSword;
        protected internal System.Windows.Forms.Button ButtonCREATE;
        protected internal System.Windows.Forms.Label LabelMSG;
        protected internal System.Windows.Forms.Label Lblaccount;
        protected internal System.Windows.Forms.Button ButtoNLOGIN;
        protected internal LimnorDatabase.WebLoginManager WebLoginManager1;
        private System.ComponentModel.IContainer components;
        protected internal LimnorDatabase.EasyDataSet EasyDataSet1;
        protected internal LimnorDatabase.EasyUpdator EasyUpdator1;
        protected internal Limnor.Net.MailSender MailSender1;
        private static Form1 _DefaultForm;
        private string valueOfNewPassword;
        /// <summary>
        /// </summary>
        public Form1()
        {
            this.InitializeComponent();
        }
        public static Form1 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form1();
                }
                return _DefaultForm;
            }
        }
        public virtual string NewPassword
        {
            get
            {
                return this.valueOfNewPassword;
            }
            set
            {
                this.valueOfNewPassword = value;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            LimnorDatabase.DbParameterListExt dbparameterlistext1 = new LimnorDatabase.DbParameterListExt();
            LimnorDatabase.SQLNoneQuery sqlnonequery1 = new LimnorDatabase.SQLNoneQuery();
            this.Label1 = new System.Windows.Forms.Label();
            this.PictureBox1 = new System.Windows.Forms.PictureBox();
            this.LabelLNM = new System.Windows.Forms.Label();
            this.LabelFNM = new System.Windows.Forms.Label();
            this.LabelSTATE = new System.Windows.Forms.Label();
            this.LabelCONTACT = new System.Windows.Forms.Label();
            this.LabelEMAIL = new System.Windows.Forms.Label();
            this.LabelLOGIN = new System.Windows.Forms.Label();
            this.LabelPASS = new System.Windows.Forms.Label();
            this.TextBoxFNM = new System.Windows.Forms.TextBox();
            this.TextBoxLNM = new System.Windows.Forms.TextBox();
            this.TextBoxSTATE = new System.Windows.Forms.TextBox();
            this.TextBoxCONTACT = new System.Windows.Forms.TextBox();
            this.TextBoxEMAIL = new System.Windows.Forms.TextBox();
            this.TextBoxLOGIN = new System.Windows.Forms.TextBox();
            this.TextBoxPASSword = new System.Windows.Forms.TextBox();
            this.ButtonCREATE = new System.Windows.Forms.Button();
            this.LabelMSG = new System.Windows.Forms.Label();
            this.Lblaccount = new System.Windows.Forms.Label();
            this.ButtoNLOGIN = new System.Windows.Forms.Button();
            this.components = new System.ComponentModel.Container();
            this.WebLoginManager1 = new LimnorDatabase.WebLoginManager(this.components);
            this.EasyDataSet1 = new LimnorDatabase.EasyDataSet();
            this.EasyUpdator1 = new LimnorDatabase.EasyUpdator(this.components);
            this.MailSender1 = new Limnor.Net.MailSender();
            ((System.ComponentModel.ISupportInitialize)(EasyDataSet1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.ForeColor = System.Drawing.Color.Navy;
            this.Label1.Location = new System.Drawing.Point(316, 20);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(220, 30);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "SIGNUP HERE";
            // 
            // PictureBox1
            // 
            this.PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("PictureBox1.Image")));
            this.PictureBox1.Location = new System.Drawing.Point(384, 53);
            this.PictureBox1.Name = "PictureBox1";
            this.PictureBox1.Size = new System.Drawing.Size(64, 44);
            this.PictureBox1.TabIndex = 1;
            this.PictureBox1.TabStop = false;
            // 
            // LabelLNM
            // 
            this.LabelLNM.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.LabelLNM.ForeColor = System.Drawing.Color.Navy;
            this.LabelLNM.Location = new System.Drawing.Point(166, 162);
            this.LabelLNM.Name = "LabelLNM";
            this.LabelLNM.Size = new System.Drawing.Size(160, 23);
            this.LabelLNM.TabIndex = 2;
            this.LabelLNM.Text = "LAST NAME";
            // 
            // LabelFNM
            // 
            this.LabelFNM.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.LabelFNM.ForeColor = System.Drawing.Color.Navy;
            this.LabelFNM.Location = new System.Drawing.Point(166, 125);
            this.LabelFNM.Name = "LabelFNM";
            this.LabelFNM.Size = new System.Drawing.Size(170, 23);
            this.LabelFNM.TabIndex = 2;
            this.LabelFNM.Text = "FIRST NAME";
            // 
            // LabelSTATE
            // 
            this.LabelSTATE.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.LabelSTATE.ForeColor = System.Drawing.Color.Navy;
            this.LabelSTATE.Location = new System.Drawing.Point(166, 200);
            this.LabelSTATE.Name = "LabelSTATE";
            this.LabelSTATE.Size = new System.Drawing.Size(94, 23);
            this.LabelSTATE.TabIndex = 2;
            this.LabelSTATE.Text = "STATE";
            // 
            // LabelCONTACT
            // 
            this.LabelCONTACT.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.LabelCONTACT.ForeColor = System.Drawing.Color.Navy;
            this.LabelCONTACT.Location = new System.Drawing.Point(166, 236);
            this.LabelCONTACT.Name = "LabelCONTACT";
            this.LabelCONTACT.Size = new System.Drawing.Size(160, 23);
            this.LabelCONTACT.TabIndex = 2;
            this.LabelCONTACT.Text = "CONTACT NO";
            // 
            // LabelEMAIL
            // 
            this.LabelEMAIL.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.LabelEMAIL.ForeColor = System.Drawing.Color.Navy;
            this.LabelEMAIL.Location = new System.Drawing.Point(166, 275);
            this.LabelEMAIL.Name = "LabelEMAIL";
            this.LabelEMAIL.Size = new System.Drawing.Size(98, 23);
            this.LabelEMAIL.TabIndex = 2;
            this.LabelEMAIL.Text = "E-MAIL";
            // 
            // LabelLOGIN
            // 
            this.LabelLOGIN.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.LabelLOGIN.ForeColor = System.Drawing.Color.Navy;
            this.LabelLOGIN.Location = new System.Drawing.Point(166, 321);
            this.LabelLOGIN.Name = "LabelLOGIN";
            this.LabelLOGIN.Size = new System.Drawing.Size(160, 23);
            this.LabelLOGIN.TabIndex = 2;
            this.LabelLOGIN.Text = "LOGIN NAME";
            // 
            // LabelPASS
            // 
            this.LabelPASS.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.LabelPASS.ForeColor = System.Drawing.Color.Navy;
            this.LabelPASS.Location = new System.Drawing.Point(166, 365);
            this.LabelPASS.Name = "LabelPASS";
            this.LabelPASS.Size = new System.Drawing.Size(160, 23);
            this.LabelPASS.TabIndex = 2;
            this.LabelPASS.Text = "PASSWORD";
            // 
            // TextBoxFNM
            // 
            this.TextBoxFNM.Location = new System.Drawing.Point(489, 125);
            this.TextBoxFNM.Name = "TextBoxFNM";
            this.TextBoxFNM.Size = new System.Drawing.Size(270, 20);
            this.TextBoxFNM.TabIndex = 3;
            // 
            // TextBoxLNM
            // 
            this.TextBoxLNM.Location = new System.Drawing.Point(489, 165);
            this.TextBoxLNM.Name = "TextBoxLNM";
            this.TextBoxLNM.Size = new System.Drawing.Size(270, 20);
            this.TextBoxLNM.TabIndex = 3;
            // 
            // TextBoxSTATE
            // 
            this.TextBoxSTATE.Location = new System.Drawing.Point(489, 203);
            this.TextBoxSTATE.Name = "TextBoxSTATE";
            this.TextBoxSTATE.Size = new System.Drawing.Size(270, 20);
            this.TextBoxSTATE.TabIndex = 3;
            // 
            // TextBoxCONTACT
            // 
            this.TextBoxCONTACT.Location = new System.Drawing.Point(489, 242);
            this.TextBoxCONTACT.Name = "TextBoxCONTACT";
            this.TextBoxCONTACT.Size = new System.Drawing.Size(270, 20);
            this.TextBoxCONTACT.TabIndex = 3;
            // 
            // TextBoxEMAIL
            // 
            this.TextBoxEMAIL.Location = new System.Drawing.Point(489, 278);
            this.TextBoxEMAIL.Name = "TextBoxEMAIL";
            this.TextBoxEMAIL.Size = new System.Drawing.Size(270, 20);
            this.TextBoxEMAIL.TabIndex = 3;
            // 
            // TextBoxLOGIN
            // 
            this.TextBoxLOGIN.Location = new System.Drawing.Point(489, 322);
            this.TextBoxLOGIN.Name = "TextBoxLOGIN";
            this.TextBoxLOGIN.Size = new System.Drawing.Size(270, 20);
            this.TextBoxLOGIN.TabIndex = 3;
            // 
            // TextBoxPASSword
            // 
            this.TextBoxPASSword.Location = new System.Drawing.Point(489, 365);
            this.TextBoxPASSword.Name = "TextBoxPASSword";
            this.TextBoxPASSword.Size = new System.Drawing.Size(270, 20);
            this.TextBoxPASSword.TabIndex = 3;
            // 
            // ButtonCREATE
            // 
            this.ButtonCREATE.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.ButtonCREATE.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.ButtonCREATE.Location = new System.Drawing.Point(489, 408);
            this.ButtonCREATE.Name = "ButtonCREATE";
            this.ButtonCREATE.Size = new System.Drawing.Size(200, 36);
            this.ButtonCREATE.TabIndex = 4;
            this.ButtonCREATE.Text = "CREATE";
            this.ButtonCREATE.UseVisualStyleBackColor = true;
            this.ButtonCREATE.Click += new System.EventHandler(this.Click_5b21a0d7);
            // 
            // LabelMSG
            // 
            this.LabelMSG.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold);
            this.LabelMSG.ForeColor = System.Drawing.Color.Black;
            this.LabelMSG.Location = new System.Drawing.Point(489, 478);
            this.LabelMSG.Name = "LabelMSG";
            this.LabelMSG.Size = new System.Drawing.Size(114, 23);
            this.LabelMSG.TabIndex = 5;
            this.LabelMSG.Text = "MESSAGE";
            // 
            // Lblaccount
            // 
            this.Lblaccount.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.Lblaccount.Location = new System.Drawing.Point(166, 551);
            this.Lblaccount.Name = "Lblaccount";
            this.Lblaccount.Size = new System.Drawing.Size(318, 31);
            this.Lblaccount.TabIndex = 3;
            this.Lblaccount.Text = "Already have an account?";
            // 
            // ButtoNLOGIN
            // 
            this.ButtoNLOGIN.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.ButtoNLOGIN.ForeColor = System.Drawing.Color.Navy;
            this.ButtoNLOGIN.Location = new System.Drawing.Point(489, 551);
            this.ButtoNLOGIN.Name = "ButtoNLOGIN";
            this.ButtoNLOGIN.Size = new System.Drawing.Size(200, 39);
            this.ButtoNLOGIN.TabIndex = 6;
            this.ButtoNLOGIN.Text = "LOGIN";
            this.ButtoNLOGIN.UseVisualStyleBackColor = true;
            this.ButtoNLOGIN.Click += new System.EventHandler(this.Click_22df9cba);
            // 
            // WebLoginManager1
            // 
            this.WebLoginManager1.ComponentName = "WebLoginManager1";
            this.WebLoginManager1.ConnectionID = new System.Guid("50dc8941-d656-4888-9c35-65ce28a08610");
            this.WebLoginManager1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.WebLoginManager1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.WebLoginManager1.FailedMessageLableId = null;
            this.WebLoginManager1.ID = new System.Guid("5866f8b1-508e-47f0-9c59-c07e6893ab70");
            this.WebLoginManager1.InactivityMinutes = 0;
            this.WebLoginManager1.LabelToShowLoginFailedMessage = null;
            this.WebLoginManager1.LoginFailedMessage = null;
            this.WebLoginManager1.LoginPermissionFailedMessage = null;
            this.WebLoginManager1.PasswordHash = WindowsUtility.EnumPasswordHash.SHA256;
            this.WebLoginManager1.UserAccountIdFieldName = "USERiD";
            this.WebLoginManager1.UserAccountLevelFieldName = "USER LEVEL";
            this.WebLoginManager1.UserAccountLoginFieldName = "LOGIN NAME";
            this.WebLoginManager1.UserAccountPasswordFieldName = "PASSWORD";
            this.WebLoginManager1.UserAccountResetCodeFieldName = "RESET CODE";
            this.WebLoginManager1.UserAccountResetCodeTimeFieldName = "RESET CODE EXPIRE";
            this.WebLoginManager1.UserAccountSaltFieldName = "SALT";
            this.WebLoginManager1.UserAccountTableName = "GLASS";
            // 
            // EasyDataSet1
            // 
            this.EasyDataSet1.ConnectionID = new System.Guid("50dc8941-d656-4888-9c35-65ce28a08610");
            this.EasyDataSet1.DataSetName = "Data_cfc53ca6-cc5c-4dad-a6bf-cc872e254d13";
            this.EasyDataSet1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.EasyDataSet1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.EasyDataSet1.Description = null;
            this.EasyDataSet1.DynamicParameters = dbparameterlistext1;
            this.EasyDataSet1.Field_DataSize = new int[] {
                    4};
            this.EasyDataSet1.Field_FieldCaption = new string[] {
                    null};
            this.EasyDataSet1.Field_FieldText = new string[] {
                    "[GLASS].[USERiD]"};
            this.EasyDataSet1.Field_FromTableName = new string[] {
                    "GLASS"};
            this.EasyDataSet1.Field_Indexed = new bool[] {
                    true};
            this.EasyDataSet1.Field_IsIdentity = new bool[] {
                    true};
            this.EasyDataSet1.Field_Name = new string[] {
                    "USERiD"};
            this.EasyDataSet1.Field_OleDbType = new System.Data.OleDb.OleDbType[] {
                    System.Data.OleDb.OleDbType.Integer};
            this.EasyDataSet1.Field_ReadOnly = new bool[] {
                    true};
            this.EasyDataSet1.From = "[GLASS]";
            this.EasyDataSet1.GroupBy = null;
            this.EasyDataSet1.Having = null;
            this.EasyDataSet1.IsFieldImage = new bool[] {
                    false};
            this.EasyDataSet1.Limit = null;
            this.EasyDataSet1.Name = "EasyDataSet1";
            this.EasyDataSet1.OrderBy = null;
            this.EasyDataSet1.Param_Name = new string[] {
                    "@loginName"};
            this.EasyDataSet1.Param_OleDbType = new System.Data.OleDb.OleDbType[] {
                    System.Data.OleDb.OleDbType.VarWChar};
            this.EasyDataSet1.Param_Value = new string[] {
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|"};
            this.EasyDataSet1.TableName = "Table4010146875";
            this.EasyDataSet1.UpdatableTableName = "GLASS";
            this.EasyDataSet1.Where = "[GLASS].[LOGIN NAME] = @loginName";
            // 
            // EasyUpdator1
            // 
            this.EasyUpdator1.ConnectionID = new System.Guid("50dc8941-d656-4888-9c35-65ce28a08610");
            this.EasyUpdator1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.EasyUpdator1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            sqlnonequery1.CommandType = LimnorDatabase.enmNonQueryType.Insert;
            sqlnonequery1.MultiRow = false;
            sqlnonequery1.Param_Name = new string[] {
                    "@FIRSTNM",
                    "@LASTNM",
                    "@STATE",
                    "@CONTACT",
                    "@EMAIL",
                    "@LOGINNM",
                    "@PASS"};
            sqlnonequery1.Param_OleDbType = new System.Data.OleDb.OleDbType[] {
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar};
            sqlnonequery1.Param_Value = new string[] {
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|",
                    "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c5" +
                        "61934e089|"};
            sqlnonequery1.SQL = "INSERT INTO [GLASS] ([FIRST NAME],[LAST NAME],[STATE],[CONTACT NO],[E-MAIL],[LOGI" +
                "N NAME],[PASSWORD])  VALUES (@FIRSTNM,@LASTNM,@STATE,@CONTACT,@EMAIL,@LOGINNM,@P" +
                "ASS)";
            sqlnonequery1.TableName = "";
            this.EasyUpdator1.ExecutionCommand = sqlnonequery1;
            this.EasyUpdator1.LastInsertID = 0;
            this.EasyUpdator1.Name = "EasyUpdator1";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.BackColor = System.Drawing.Color.Teal;
            this.ClientSize = new System.Drawing.Size(917, 618);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.PictureBox1);
            this.Controls.Add(this.LabelLNM);
            this.Controls.Add(this.LabelFNM);
            this.Controls.Add(this.LabelSTATE);
            this.Controls.Add(this.LabelCONTACT);
            this.Controls.Add(this.LabelEMAIL);
            this.Controls.Add(this.LabelLOGIN);
            this.Controls.Add(this.LabelPASS);
            this.Controls.Add(this.TextBoxFNM);
            this.Controls.Add(this.TextBoxLNM);
            this.Controls.Add(this.TextBoxSTATE);
            this.Controls.Add(this.TextBoxCONTACT);
            this.Controls.Add(this.TextBoxEMAIL);
            this.Controls.Add(this.TextBoxLOGIN);
            this.Controls.Add(this.TextBoxPASSword);
            this.Controls.Add(this.ButtonCREATE);
            this.Controls.Add(this.LabelMSG);
            this.Controls.Add(this.Lblaccount);
            this.Controls.Add(this.ButtoNLOGIN);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form1";
            this.Text = "Form1";
            WebLoginManager1.CreateDataTable();
            EasyDataSet1.CreateDataTable();
            EasyDataSet1.Query();
            ((System.ComponentModel.ISupportInitialize)(EasyDataSet1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_5b21a0d7(object sender, System.EventArgs e)
        {
            if ((string.IsNullOrEmpty(this.TextBoxLOGIN.Text) || string.IsNullOrEmpty(this.TextBoxEMAIL.Text)))
            {
                return;
            }
            this.EasyDataSet1.QueryWithParameterValues(this.TextBoxLOGIN.Text);
            if (this.EasyDataSet1.HasData)
            {
                return;
            }
            this.EasyUpdator1.ExecuteWithParameterValues(this.TextBoxFNM.Text, this.TextBoxLNM.Text, this.TextBoxSTATE.Text, this.TextBoxCONTACT.Text, this.TextBoxEMAIL.Text, this.TextBoxLOGIN.Text, this.TextBoxPASSword.Text);
            this.NewPassword = WindowsUtility.WinUtil.GetRandomString(10);
            this.WebLoginManager1.ResetPassword(this.TextBoxLOGIN.Text, this.NewPassword);
            this.MailSender1.Body = string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}{2}{3}{4}", new object[] {
                        "Your account is created.Login name is:",
                        this.TextBoxLOGIN.Text,
                        ",password is: ",
                        this.NewPassword,
                        ".You need to change your password as soon as possible."});
            this.MailSender1.AddRecipient(this.TextBoxEMAIL.Text, null, Limnor.Net.EnumCharEncode.Default);
            this.MailSender1.Send();
            this.MailSender1.ClearRecipients();
            System.Windows.Forms.MessageBox.Show(this, "A new user account is created.");
            Form3.DefaultForm.Show(this);
        }
        private void Click_22df9cba(object sender, System.EventArgs e)
        {
            Form2.DefaultForm.Show(this);
        }
        protected override void Dispose(bool disposing)
        {
            if ((disposing 
                        && (components != null)))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
