//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Windows.Forms;
    using System.Drawing;
    using LimnorDatabase;
    
    public class Form2 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label LBLWEL;
        protected internal System.Windows.Forms.Label Labelhead;
        protected internal System.Windows.Forms.PictureBox PictureBox1;
        protected internal System.Windows.Forms.Label LabelLOGIN;
        protected internal System.Windows.Forms.Label LabelPASS;
        protected internal System.Windows.Forms.TextBox TEXTBOXLOGIN;
        protected internal System.Windows.Forms.TextBox TextBoxPASS;
        protected internal System.Windows.Forms.Button BTNSUBMIT;
        protected internal System.Windows.Forms.Label LABELMSG;
        protected internal System.Windows.Forms.Button Buttonsignup;
        protected internal System.Windows.Forms.Label Lblsign;
        protected internal LimnorDatabase.WebLoginManager WebLoginManager1;
        private System.ComponentModel.IContainer components;
        private static Form2 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form2()
        {
            this.InitializeComponent();
        }
        public static Form2 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form2();
                }
                return _DefaultForm;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            this.LBLWEL = new System.Windows.Forms.Label();
            this.Labelhead = new System.Windows.Forms.Label();
            this.PictureBox1 = new System.Windows.Forms.PictureBox();
            this.LabelLOGIN = new System.Windows.Forms.Label();
            this.LabelPASS = new System.Windows.Forms.Label();
            this.TEXTBOXLOGIN = new System.Windows.Forms.TextBox();
            this.TextBoxPASS = new System.Windows.Forms.TextBox();
            this.BTNSUBMIT = new System.Windows.Forms.Button();
            this.LABELMSG = new System.Windows.Forms.Label();
            this.Buttonsignup = new System.Windows.Forms.Button();
            this.Lblsign = new System.Windows.Forms.Label();
            this.components = new System.ComponentModel.Container();
            this.WebLoginManager1 = new LimnorDatabase.WebLoginManager(this.components);
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // LBLWEL
            // 
            this.LBLWEL.Font = new System.Drawing.Font("Arial Rounded MT Bold", 24F);
            this.LBLWEL.Location = new System.Drawing.Point(368, 12);
            this.LBLWEL.Name = "LBLWEL";
            this.LBLWEL.Size = new System.Drawing.Size(190, 47);
            this.LBLWEL.TabIndex = 0;
            this.LBLWEL.Text = "WELCOME";
            // 
            // Labelhead
            // 
            this.Labelhead.Font = new System.Drawing.Font("Algerian", 20.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Labelhead.ForeColor = System.Drawing.Color.Navy;
            this.Labelhead.Location = new System.Drawing.Point(368, 59);
            this.Labelhead.Name = "Labelhead";
            this.Labelhead.Size = new System.Drawing.Size(175, 29);
            this.Labelhead.TabIndex = 1;
            this.Labelhead.Text = "LOGIN HERE";
            // 
            // PictureBox1
            // 
            this.PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("PictureBox1.Image")));
            this.PictureBox1.Location = new System.Drawing.Point(420, 104);
            this.PictureBox1.Name = "PictureBox1";
            this.PictureBox1.Size = new System.Drawing.Size(51, 50);
            this.PictureBox1.TabIndex = 2;
            this.PictureBox1.TabStop = false;
            // 
            // LabelLOGIN
            // 
            this.LabelLOGIN.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.LabelLOGIN.ForeColor = System.Drawing.Color.Navy;
            this.LabelLOGIN.Location = new System.Drawing.Point(190, 189);
            this.LabelLOGIN.Name = "LabelLOGIN";
            this.LabelLOGIN.Size = new System.Drawing.Size(180, 33);
            this.LabelLOGIN.TabIndex = 0;
            this.LabelLOGIN.Text = "LOGIN NAME";
            // 
            // LabelPASS
            // 
            this.LabelPASS.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.LabelPASS.ForeColor = System.Drawing.Color.Navy;
            this.LabelPASS.Location = new System.Drawing.Point(190, 272);
            this.LabelPASS.Name = "LabelPASS";
            this.LabelPASS.Size = new System.Drawing.Size(161, 34);
            this.LabelPASS.TabIndex = 0;
            this.LabelPASS.Text = "PASSWORD";
            // 
            // TEXTBOXLOGIN
            // 
            this.TEXTBOXLOGIN.Location = new System.Drawing.Point(449, 189);
            this.TEXTBOXLOGIN.Name = "TEXTBOXLOGIN";
            this.TEXTBOXLOGIN.Size = new System.Drawing.Size(281, 20);
            this.TEXTBOXLOGIN.TabIndex = 3;
            // 
            // TextBoxPASS
            // 
            this.TextBoxPASS.Location = new System.Drawing.Point(449, 281);
            this.TextBoxPASS.Name = "TextBoxPASS";
            this.TextBoxPASS.Size = new System.Drawing.Size(281, 20);
            this.TextBoxPASS.TabIndex = 3;
            // 
            // BTNSUBMIT
            // 
            this.BTNSUBMIT.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.BTNSUBMIT.ForeColor = System.Drawing.Color.Navy;
            this.BTNSUBMIT.Location = new System.Drawing.Point(449, 344);
            this.BTNSUBMIT.Name = "BTNSUBMIT";
            this.BTNSUBMIT.Size = new System.Drawing.Size(116, 34);
            this.BTNSUBMIT.TabIndex = 4;
            this.BTNSUBMIT.Text = "SUBMIT";
            this.BTNSUBMIT.UseVisualStyleBackColor = true;
            this.BTNSUBMIT.Click += new System.EventHandler(this.Click_1f72139d);
            // 
            // LABELMSG
            // 
            this.LABELMSG.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.LABELMSG.ForeColor = System.Drawing.Color.Navy;
            this.LABELMSG.Location = new System.Drawing.Point(449, 419);
            this.LABELMSG.Name = "LABELMSG";
            this.LABELMSG.Size = new System.Drawing.Size(116, 23);
            this.LABELMSG.TabIndex = 5;
            this.LABELMSG.Text = "   MESSAGE";
            // 
            // Buttonsignup
            // 
            this.Buttonsignup.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold);
            this.Buttonsignup.ForeColor = System.Drawing.Color.Navy;
            this.Buttonsignup.Location = new System.Drawing.Point(449, 488);
            this.Buttonsignup.Name = "Buttonsignup";
            this.Buttonsignup.Size = new System.Drawing.Size(122, 38);
            this.Buttonsignup.TabIndex = 6;
            this.Buttonsignup.Text = "SIGNUP";
            this.Buttonsignup.UseVisualStyleBackColor = true;
            this.Buttonsignup.Click += new System.EventHandler(this.Click_125efacd);
            // 
            // Lblsign
            // 
            this.Lblsign.Font = new System.Drawing.Font("Microsoft Sans Serif", 21.75F, System.Drawing.FontStyle.Bold);
            this.Lblsign.Location = new System.Drawing.Point(190, 488);
            this.Lblsign.Name = "Lblsign";
            this.Lblsign.Size = new System.Drawing.Size(239, 38);
            this.Lblsign.TabIndex = 3;
            this.Lblsign.Text = "First time here?";
            // 
            // WebLoginManager1
            // 
            this.WebLoginManager1.ComponentName = "WebLoginManager1";
            this.WebLoginManager1.ConnectionID = new System.Guid("50dc8941-d656-4888-9c35-65ce28a08610");
            this.WebLoginManager1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.WebLoginManager1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.WebLoginManager1.FailedMessageLableId = "LABELMSG";
            this.WebLoginManager1.ID = new System.Guid("99c27aed-11c7-42f2-b9f6-ddcfae9a2a15");
            this.WebLoginManager1.InactivityMinutes = 10;
            this.WebLoginManager1.LabelToShowLoginFailedMessage = this.LABELMSG;
            this.WebLoginManager1.LoginFailedMessage = null;
            this.WebLoginManager1.LoginPermissionFailedMessage = null;
            this.WebLoginManager1.PasswordHash = WindowsUtility.EnumPasswordHash.MD5;
            this.WebLoginManager1.UserAccountIdFieldName = "USERiD";
            this.WebLoginManager1.UserAccountLevelFieldName = "USER LEVEL";
            this.WebLoginManager1.UserAccountLoginFieldName = "LOGIN NAME";
            this.WebLoginManager1.UserAccountPasswordFieldName = "PASSWORD";
            this.WebLoginManager1.UserAccountResetCodeFieldName = "RESET CODE";
            this.WebLoginManager1.UserAccountResetCodeTimeFieldName = "RESET CODE EXPIRE";
            this.WebLoginManager1.UserAccountSaltFieldName = "SALT";
            this.WebLoginManager1.UserAccountTableName = "GLASS";
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.BackColor = System.Drawing.Color.Teal;
            this.ClientSize = new System.Drawing.Size(917, 618);
            this.Controls.Add(this.LBLWEL);
            this.Controls.Add(this.Labelhead);
            this.Controls.Add(this.PictureBox1);
            this.Controls.Add(this.LabelLOGIN);
            this.Controls.Add(this.LabelPASS);
            this.Controls.Add(this.TEXTBOXLOGIN);
            this.Controls.Add(this.TextBoxPASS);
            this.Controls.Add(this.BTNSUBMIT);
            this.Controls.Add(this.LABELMSG);
            this.Controls.Add(this.Buttonsignup);
            this.Controls.Add(this.Lblsign);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form2";
            this.Text = "Form2";
            WebLoginManager1.CreateDataTable();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_1f72139d(object sender, System.EventArgs e)
        {
            this.WebLoginManager1.Login(this.TEXTBOXLOGIN.Text, this.TextBoxPASS.Text);
        }
        private void Click_125efacd(object sender, System.EventArgs e)
        {
            Form1.DefaultForm.Show(this);
            Form1.DefaultForm.Show(this);
        }
        protected override void Dispose(bool disposing)
        {
            if ((disposing 
                        && (components != null)))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
