//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    using LimnorDatabase;
    using System.Data.OleDb;
    
    public class Form3 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label LabelHEAD;
        protected internal System.Windows.Forms.DateTimePicker DateTimePicker1;
        protected internal LimnorDatabase.EasyGrid EasyGrid1;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn1;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn2;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn3;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn4;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn5;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn6;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn7;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn8;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn9;
        protected internal System.Windows.Forms.DataGridViewTextBoxColumn DataGridViewTextBoxColumn10;
        private System.ComponentModel.IContainer components;
        protected internal System.Windows.Forms.Label Label2;
        protected internal System.Windows.Forms.GroupBox GroupBox1;
        protected internal System.Windows.Forms.ComboBox ComboBoxdimensions;
        protected internal System.Windows.Forms.ComboBox ComboBoxglasstype;
        protected internal System.Windows.Forms.Label LabelNM;
        protected internal System.Windows.Forms.Label LabelDIMEN;
        protected internal System.Windows.Forms.Label LabelGLSTYPE;
        protected internal System.Windows.Forms.Label Labeldetails;
        protected internal System.Windows.Forms.CheckBox CheckBoxPURCH;
        protected internal System.Windows.Forms.Label LabelADD;
        protected internal System.Windows.Forms.CheckBox CheckBoxADD;
        protected internal System.Windows.Forms.Label LabelCONT;
        protected internal System.Windows.Forms.CheckBox CheckBoxCUT;
        protected internal System.Windows.Forms.Label LabelTASK;
        protected internal System.Windows.Forms.TextBox TextBoxNM;
        protected internal System.Windows.Forms.CheckBox CheckBoxGRIND;
        protected internal System.Windows.Forms.TextBox TextBoxADD;
        protected internal System.Windows.Forms.TextBox TextBoxCONT;
        protected internal System.Windows.Forms.GroupBox GroupBox2;
        protected internal System.Windows.Forms.Button ButtoNSAVE;
        protected internal System.Windows.Forms.Label Label10;
        protected internal System.Windows.Forms.Label LabelLCHR;
        protected internal System.Windows.Forms.Label LabelFCHR;
        protected internal System.Windows.Forms.TextBox TextBoxFCHR;
        protected internal System.Windows.Forms.Label Labelcostcal;
        protected internal System.Windows.Forms.Button ButtonCALC;
        protected internal System.Windows.Forms.TextBox TextBoxLCHR;
        protected internal System.Windows.Forms.Button ButtonUPDATE;
        protected internal System.Windows.Forms.Label LabelADDCHR;
        protected internal System.Windows.Forms.Button ButtonDEL;
        protected internal System.Windows.Forms.Label LabelAMOUNTCHR;
        protected internal System.Windows.Forms.TextBox TextBoxAMOUNT;
        protected internal System.Windows.Forms.TextBox TextBoxADDCHR;
        protected internal System.Windows.Forms.Button Buttonsearch;
        protected internal System.Windows.Forms.TextBox TextBoxsearch;
        protected internal System.Windows.Forms.Button Button2147483646;
        protected internal System.Windows.Forms.Button Buttonviewds;
        protected internal System.Windows.Forms.Label Label12;
        protected internal System.Windows.Forms.ComboBox ComboBox3;
        protected internal System.Windows.Forms.Button Buttonnext;
        protected internal System.Windows.Forms.Button Buttonprevios;
        protected internal System.Windows.Forms.Button Buttonpending;
        protected internal LimnorDatabase.WebLoginManager WebLoginManager1;
        protected internal LimnorDatabase.EasyDataSet EasyDataSet1;
        private static Form3 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form3()
        {
            this.InitializeComponent();
        }
        public static Form3 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form3();
                }
                return _DefaultForm;
            }
        }
        private void InitializeComponent()
        {
            LimnorDatabase.DbParameterListExt dbparameterlistext1 = new LimnorDatabase.DbParameterListExt();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form3));
            this.LabelHEAD = new System.Windows.Forms.Label();
            this.DateTimePicker1 = new System.Windows.Forms.DateTimePicker();
            this.Label2 = new System.Windows.Forms.Label();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.ComboBoxdimensions = new System.Windows.Forms.ComboBox();
            this.ComboBoxglasstype = new System.Windows.Forms.ComboBox();
            this.LabelNM = new System.Windows.Forms.Label();
            this.LabelDIMEN = new System.Windows.Forms.Label();
            this.LabelGLSTYPE = new System.Windows.Forms.Label();
            this.Labeldetails = new System.Windows.Forms.Label();
            this.CheckBoxPURCH = new System.Windows.Forms.CheckBox();
            this.LabelADD = new System.Windows.Forms.Label();
            this.CheckBoxADD = new System.Windows.Forms.CheckBox();
            this.LabelCONT = new System.Windows.Forms.Label();
            this.CheckBoxCUT = new System.Windows.Forms.CheckBox();
            this.LabelTASK = new System.Windows.Forms.Label();
            this.TextBoxNM = new System.Windows.Forms.TextBox();
            this.CheckBoxGRIND = new System.Windows.Forms.CheckBox();
            this.TextBoxADD = new System.Windows.Forms.TextBox();
            this.TextBoxCONT = new System.Windows.Forms.TextBox();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.ButtoNSAVE = new System.Windows.Forms.Button();
            this.Label10 = new System.Windows.Forms.Label();
            this.LabelLCHR = new System.Windows.Forms.Label();
            this.LabelFCHR = new System.Windows.Forms.Label();
            this.TextBoxFCHR = new System.Windows.Forms.TextBox();
            this.Labelcostcal = new System.Windows.Forms.Label();
            this.ButtonCALC = new System.Windows.Forms.Button();
            this.TextBoxLCHR = new System.Windows.Forms.TextBox();
            this.ButtonUPDATE = new System.Windows.Forms.Button();
            this.LabelADDCHR = new System.Windows.Forms.Label();
            this.ButtonDEL = new System.Windows.Forms.Button();
            this.LabelAMOUNTCHR = new System.Windows.Forms.Label();
            this.TextBoxAMOUNT = new System.Windows.Forms.TextBox();
            this.TextBoxADDCHR = new System.Windows.Forms.TextBox();
            this.Buttonsearch = new System.Windows.Forms.Button();
            this.TextBoxsearch = new System.Windows.Forms.TextBox();
            this.EasyGrid1 = new LimnorDatabase.EasyGrid();
            this.components = new System.ComponentModel.Container();
            this.DataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn5 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn6 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn7 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn8 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn9 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.DataGridViewTextBoxColumn10 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Button2147483646 = new System.Windows.Forms.Button();
            this.Buttonviewds = new System.Windows.Forms.Button();
            this.Label12 = new System.Windows.Forms.Label();
            this.ComboBox3 = new System.Windows.Forms.ComboBox();
            this.Buttonnext = new System.Windows.Forms.Button();
            this.Buttonprevios = new System.Windows.Forms.Button();
            this.Buttonpending = new System.Windows.Forms.Button();
            this.WebLoginManager1 = new LimnorDatabase.WebLoginManager(this.components);
            this.EasyDataSet1 = new LimnorDatabase.EasyDataSet();
            this.GroupBox1.SuspendLayout();
            this.GroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(EasyDataSet1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(EasyGrid1)).BeginInit();
            this.SuspendLayout();
            // 
            // LabelHEAD
            // 
            this.LabelHEAD.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Bold);
            this.LabelHEAD.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.LabelHEAD.Location = new System.Drawing.Point(412, 9);
            this.LabelHEAD.Name = "LabelHEAD";
            this.LabelHEAD.Size = new System.Drawing.Size(399, 34);
            this.LabelHEAD.TabIndex = 0;
            this.LabelHEAD.Text = "CUSTOMER DETAILS PORTAL";
            // 
            // DateTimePicker1
            // 
            this.DateTimePicker1.Location = new System.Drawing.Point(132, 53);
            this.DateTimePicker1.Name = "DateTimePicker1";
            this.DateTimePicker1.Size = new System.Drawing.Size(200, 20);
            this.DateTimePicker1.TabIndex = 2;
            this.DateTimePicker1.Value = new System.DateTime(2019, 8, 30, 19, 21, 0, 0);
            // 
            // Label2
            // 
            this.Label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.Label2.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label2.Location = new System.Drawing.Point(78, 53);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(48, 23);
            this.Label2.TabIndex = 1;
            this.Label2.Text = "INFO";
            // 
            // GroupBox1
            // 
            this.GroupBox1.Controls.Add(this.ComboBoxdimensions);
            this.GroupBox1.Controls.Add(this.ComboBoxglasstype);
            this.GroupBox1.Controls.Add(this.LabelNM);
            this.GroupBox1.Controls.Add(this.LabelDIMEN);
            this.GroupBox1.Controls.Add(this.LabelGLSTYPE);
            this.GroupBox1.Controls.Add(this.Labeldetails);
            this.GroupBox1.Controls.Add(this.CheckBoxPURCH);
            this.GroupBox1.Controls.Add(this.LabelADD);
            this.GroupBox1.Controls.Add(this.CheckBoxADD);
            this.GroupBox1.Controls.Add(this.LabelCONT);
            this.GroupBox1.Controls.Add(this.CheckBoxCUT);
            this.GroupBox1.Controls.Add(this.LabelTASK);
            this.GroupBox1.Controls.Add(this.TextBoxNM);
            this.GroupBox1.Controls.Add(this.CheckBoxGRIND);
            this.GroupBox1.Controls.Add(this.TextBoxADD);
            this.GroupBox1.Controls.Add(this.TextBoxCONT);
            this.GroupBox1.Location = new System.Drawing.Point(41, 96);
            this.GroupBox1.Name = "GroupBox1";
            this.GroupBox1.Size = new System.Drawing.Size(1106, 196);
            this.GroupBox1.TabIndex = 3;
            this.GroupBox1.TabStop = false;
            this.GroupBox1.Text = "GroupBox1";
            // 
            // ComboBoxdimensions
            // 
            this.ComboBoxdimensions.FormattingEnabled = true;
            this.ComboBoxdimensions.Items.AddRange(new object[] {
                        "dimension(mm)\tprice(rs)",
                        "0-3\t\t3,218",
                        "3-6\t\t4,827",
                        "6-9\t\t6,435",
                        "9-12\t\t8,044",
                        "12-36\t\t10,940",
                        "36-48\t\t12,870"});
            this.ComboBoxdimensions.Location = new System.Drawing.Point(741, 69);
            this.ComboBoxdimensions.Name = "ComboBoxdimensions";
            this.ComboBoxdimensions.Size = new System.Drawing.Size(301, 21);
            this.ComboBoxdimensions.TabIndex = 5;
            this.ComboBoxdimensions.Text = "Choose  dimension of glass you want";
            // 
            // ComboBoxglasstype
            // 
            this.ComboBoxglasstype.FormattingEnabled = true;
            this.ComboBoxglasstype.Items.AddRange(new object[] {
                        "Toughened Glass",
                        "Float Glass",
                        "Laminated Glass",
                        "Tinted Glass",
                        "Mirrored Glass",
                        "Obscured Glass"});
            this.ComboBoxglasstype.Location = new System.Drawing.Point(741, 30);
            this.ComboBoxglasstype.Name = "ComboBoxglasstype";
            this.ComboBoxglasstype.Size = new System.Drawing.Size(301, 21);
            this.ComboBoxglasstype.TabIndex = 5;
            this.ComboBoxglasstype.Text = "Enter the glass type";
            // 
            // LabelNM
            // 
            this.LabelNM.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.LabelNM.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.LabelNM.Location = new System.Drawing.Point(38, 28);
            this.LabelNM.Name = "LabelNM";
            this.LabelNM.Size = new System.Drawing.Size(62, 23);
            this.LabelNM.TabIndex = 8;
            this.LabelNM.Text = "NAME";
            // 
            // LabelDIMEN
            // 
            this.LabelDIMEN.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.LabelDIMEN.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.LabelDIMEN.Location = new System.Drawing.Point(586, 67);
            this.LabelDIMEN.Name = "LabelDIMEN";
            this.LabelDIMEN.Size = new System.Drawing.Size(120, 23);
            this.LabelDIMEN.TabIndex = 8;
            this.LabelDIMEN.Text = "DIMENSION";
            // 
            // LabelGLSTYPE
            // 
            this.LabelGLSTYPE.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.LabelGLSTYPE.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.LabelGLSTYPE.Location = new System.Drawing.Point(586, 28);
            this.LabelGLSTYPE.Name = "LabelGLSTYPE";
            this.LabelGLSTYPE.Size = new System.Drawing.Size(120, 23);
            this.LabelGLSTYPE.TabIndex = 8;
            this.LabelGLSTYPE.Text = "GLASS TYPE";
            // 
            // Labeldetails
            // 
            this.Labeldetails.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.Labeldetails.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Labeldetails.Location = new System.Drawing.Point(0, 0);
            this.Labeldetails.Name = "Labeldetails";
            this.Labeldetails.Size = new System.Drawing.Size(121, 23);
            this.Labeldetails.TabIndex = 6;
            this.Labeldetails.Text = "DETAILS HERE";
            // 
            // CheckBoxPURCH
            // 
            this.CheckBoxPURCH.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.CheckBoxPURCH.Location = new System.Drawing.Point(741, 144);
            this.CheckBoxPURCH.Name = "CheckBoxPURCH";
            this.CheckBoxPURCH.Size = new System.Drawing.Size(113, 24);
            this.CheckBoxPURCH.TabIndex = 9;
            this.CheckBoxPURCH.Text = "PURCHASE";
            this.CheckBoxPURCH.UseVisualStyleBackColor = true;
            // 
            // LabelADD
            // 
            this.LabelADD.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.LabelADD.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.LabelADD.Location = new System.Drawing.Point(38, 66);
            this.LabelADD.Name = "LabelADD";
            this.LabelADD.Size = new System.Drawing.Size(87, 23);
            this.LabelADD.TabIndex = 8;
            this.LabelADD.Text = "ADDRESS";
            // 
            // CheckBoxADD
            // 
            this.CheckBoxADD.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.CheckBoxADD.Location = new System.Drawing.Point(586, 144);
            this.CheckBoxADD.Name = "CheckBoxADD";
            this.CheckBoxADD.Size = new System.Drawing.Size(104, 24);
            this.CheckBoxADD.TabIndex = 9;
            this.CheckBoxADD.Text = "ADDING";
            this.CheckBoxADD.UseVisualStyleBackColor = true;
            // 
            // LabelCONT
            // 
            this.LabelCONT.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold);
            this.LabelCONT.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.LabelCONT.Location = new System.Drawing.Point(38, 107);
            this.LabelCONT.Name = "LabelCONT";
            this.LabelCONT.Size = new System.Drawing.Size(87, 23);
            this.LabelCONT.TabIndex = 8;
            this.LabelCONT.Text = "CONTACT";
            // 
            // CheckBoxCUT
            // 
            this.CheckBoxCUT.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.CheckBoxCUT.Location = new System.Drawing.Point(383, 145);
            this.CheckBoxCUT.Name = "CheckBoxCUT";
            this.CheckBoxCUT.Size = new System.Drawing.Size(104, 24);
            this.CheckBoxCUT.TabIndex = 9;
            this.CheckBoxCUT.Text = "CUTTING";
            this.CheckBoxCUT.UseVisualStyleBackColor = true;
            // 
            // LabelTASK
            // 
            this.LabelTASK.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.LabelTASK.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.LabelTASK.Location = new System.Drawing.Point(38, 145);
            this.LabelTASK.Name = "LabelTASK";
            this.LabelTASK.Size = new System.Drawing.Size(106, 23);
            this.LabelTASK.TabIndex = 8;
            this.LabelTASK.Text = "TASK TYPE";
            // 
            // TextBoxNM
            // 
            this.TextBoxNM.Location = new System.Drawing.Point(186, 28);
            this.TextBoxNM.Name = "TextBoxNM";
            this.TextBoxNM.Size = new System.Drawing.Size(301, 20);
            this.TextBoxNM.TabIndex = 8;
            // 
            // CheckBoxGRIND
            // 
            this.CheckBoxGRIND.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.CheckBoxGRIND.Location = new System.Drawing.Point(186, 145);
            this.CheckBoxGRIND.Name = "CheckBoxGRIND";
            this.CheckBoxGRIND.Size = new System.Drawing.Size(104, 24);
            this.CheckBoxGRIND.TabIndex = 8;
            this.CheckBoxGRIND.Text = "GRINDING";
            this.CheckBoxGRIND.UseVisualStyleBackColor = true;
            // 
            // TextBoxADD
            // 
            this.TextBoxADD.Location = new System.Drawing.Point(186, 66);
            this.TextBoxADD.Name = "TextBoxADD";
            this.TextBoxADD.Size = new System.Drawing.Size(301, 20);
            this.TextBoxADD.TabIndex = 8;
            // 
            // TextBoxCONT
            // 
            this.TextBoxCONT.Location = new System.Drawing.Point(186, 107);
            this.TextBoxCONT.Name = "TextBoxCONT";
            this.TextBoxCONT.Size = new System.Drawing.Size(301, 20);
            this.TextBoxCONT.TabIndex = 8;
            // 
            // GroupBox2
            // 
            this.GroupBox2.Controls.Add(this.ButtoNSAVE);
            this.GroupBox2.Controls.Add(this.Label10);
            this.GroupBox2.Controls.Add(this.LabelLCHR);
            this.GroupBox2.Controls.Add(this.LabelFCHR);
            this.GroupBox2.Controls.Add(this.TextBoxFCHR);
            this.GroupBox2.Controls.Add(this.Labelcostcal);
            this.GroupBox2.Controls.Add(this.ButtonCALC);
            this.GroupBox2.Controls.Add(this.TextBoxLCHR);
            this.GroupBox2.Controls.Add(this.ButtonUPDATE);
            this.GroupBox2.Controls.Add(this.LabelADDCHR);
            this.GroupBox2.Controls.Add(this.ButtonDEL);
            this.GroupBox2.Controls.Add(this.LabelAMOUNTCHR);
            this.GroupBox2.Controls.Add(this.TextBoxAMOUNT);
            this.GroupBox2.Controls.Add(this.TextBoxADDCHR);
            this.GroupBox2.Location = new System.Drawing.Point(41, 314);
            this.GroupBox2.Name = "GroupBox2";
            this.GroupBox2.Size = new System.Drawing.Size(1106, 123);
            this.GroupBox2.TabIndex = 4;
            this.GroupBox2.TabStop = false;
            this.GroupBox2.Text = "GroupBox2";
            // 
            // ButtoNSAVE
            // 
            this.ButtoNSAVE.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.ButtoNSAVE.Location = new System.Drawing.Point(825, 42);
            this.ButtoNSAVE.Name = "ButtoNSAVE";
            this.ButtoNSAVE.Size = new System.Drawing.Size(101, 23);
            this.ButtoNSAVE.TabIndex = 11;
            this.ButtoNSAVE.Text = "SAVE";
            this.ButtoNSAVE.UseVisualStyleBackColor = true;
            // 
            // Label10
            // 
            this.Label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.Label10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Label10.Location = new System.Drawing.Point(59, 287);
            this.Label10.Name = "Label10";
            this.Label10.Size = new System.Drawing.Size(162, 24);
            this.Label10.TabIndex = 10;
            this.Label10.Text = "COST CALCULATION";
            // 
            // LabelLCHR
            // 
            this.LabelLCHR.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.LabelLCHR.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.LabelLCHR.Location = new System.Drawing.Point(25, 42);
            this.LabelLCHR.Name = "LabelLCHR";
            this.LabelLCHR.Size = new System.Drawing.Size(87, 23);
            this.LabelLCHR.TabIndex = 11;
            this.LabelLCHR.Text = "LABOUR C";
            // 
            // LabelFCHR
            // 
            this.LabelFCHR.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.LabelFCHR.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.LabelFCHR.Location = new System.Drawing.Point(25, 83);
            this.LabelFCHR.Name = "LabelFCHR";
            this.LabelFCHR.Size = new System.Drawing.Size(95, 23);
            this.LabelFCHR.TabIndex = 11;
            this.LabelFCHR.Text = "FREIGHT C";
            // 
            // TextBoxFCHR
            // 
            this.TextBoxFCHR.Location = new System.Drawing.Point(151, 82);
            this.TextBoxFCHR.Name = "TextBoxFCHR";
            this.TextBoxFCHR.Size = new System.Drawing.Size(218, 20);
            this.TextBoxFCHR.TabIndex = 11;
            // 
            // Labelcostcal
            // 
            this.Labelcostcal.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.Labelcostcal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.Labelcostcal.Location = new System.Drawing.Point(6, 0);
            this.Labelcostcal.Name = "Labelcostcal";
            this.Labelcostcal.Size = new System.Drawing.Size(162, 24);
            this.Labelcostcal.TabIndex = 10;
            this.Labelcostcal.Text = "COST CALCULATION";
            // 
            // ButtonCALC
            // 
            this.ButtonCALC.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.ButtonCALC.Location = new System.Drawing.Point(950, 38);
            this.ButtonCALC.Name = "ButtonCALC";
            this.ButtonCALC.Size = new System.Drawing.Size(97, 23);
            this.ButtonCALC.TabIndex = 11;
            this.ButtonCALC.Text = "CALC";
            this.ButtonCALC.UseVisualStyleBackColor = true;
            // 
            // TextBoxLCHR
            // 
            this.TextBoxLCHR.Location = new System.Drawing.Point(151, 41);
            this.TextBoxLCHR.Name = "TextBoxLCHR";
            this.TextBoxLCHR.Size = new System.Drawing.Size(218, 20);
            this.TextBoxLCHR.TabIndex = 11;
            this.TextBoxLCHR.Click += new System.EventHandler(this.Click_38f61cdd);
            // 
            // ButtonUPDATE
            // 
            this.ButtonUPDATE.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.ButtonUPDATE.Location = new System.Drawing.Point(950, 78);
            this.ButtonUPDATE.Name = "ButtonUPDATE";
            this.ButtonUPDATE.Size = new System.Drawing.Size(97, 23);
            this.ButtonUPDATE.TabIndex = 11;
            this.ButtonUPDATE.Text = "UPDATE";
            this.ButtonUPDATE.UseVisualStyleBackColor = true;
            // 
            // LabelADDCHR
            // 
            this.LabelADDCHR.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.LabelADDCHR.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.LabelADDCHR.Location = new System.Drawing.Point(399, 42);
            this.LabelADDCHR.Name = "LabelADDCHR";
            this.LabelADDCHR.Size = new System.Drawing.Size(119, 23);
            this.LabelADDCHR.TabIndex = 11;
            this.LabelADDCHR.Text = "ADDITIONAL C";
            // 
            // ButtonDEL
            // 
            this.ButtonDEL.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.ButtonDEL.Location = new System.Drawing.Point(825, 78);
            this.ButtonDEL.Name = "ButtonDEL";
            this.ButtonDEL.Size = new System.Drawing.Size(101, 23);
            this.ButtonDEL.TabIndex = 11;
            this.ButtonDEL.Text = "DELETE";
            this.ButtonDEL.UseVisualStyleBackColor = true;
            // 
            // LabelAMOUNTCHR
            // 
            this.LabelAMOUNTCHR.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold);
            this.LabelAMOUNTCHR.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.LabelAMOUNTCHR.Location = new System.Drawing.Point(399, 82);
            this.LabelAMOUNTCHR.Name = "LabelAMOUNTCHR";
            this.LabelAMOUNTCHR.Size = new System.Drawing.Size(78, 23);
            this.LabelAMOUNTCHR.TabIndex = 11;
            this.LabelAMOUNTCHR.Text = "AMOUNT";
            // 
            // TextBoxAMOUNT
            // 
            this.TextBoxAMOUNT.Location = new System.Drawing.Point(534, 81);
            this.TextBoxAMOUNT.Name = "TextBoxAMOUNT";
            this.TextBoxAMOUNT.Size = new System.Drawing.Size(239, 20);
            this.TextBoxAMOUNT.TabIndex = 11;
            this.TextBoxAMOUNT.Click += new System.EventHandler(this.Click_b7e1f75);
            // 
            // TextBoxADDCHR
            // 
            this.TextBoxADDCHR.Location = new System.Drawing.Point(534, 42);
            this.TextBoxADDCHR.Name = "TextBoxADDCHR";
            this.TextBoxADDCHR.Size = new System.Drawing.Size(239, 20);
            this.TextBoxADDCHR.TabIndex = 11;
            // 
            // Buttonsearch
            // 
            this.Buttonsearch.Location = new System.Drawing.Point(1072, 54);
            this.Buttonsearch.Name = "Buttonsearch";
            this.Buttonsearch.Size = new System.Drawing.Size(75, 23);
            this.Buttonsearch.TabIndex = 5;
            this.Buttonsearch.Text = "Search";
            this.Buttonsearch.UseVisualStyleBackColor = true;
            // 
            // TextBoxsearch
            // 
            this.TextBoxsearch.Location = new System.Drawing.Point(809, 58);
            this.TextBoxsearch.Name = "TextBoxsearch";
            this.TextBoxsearch.Size = new System.Drawing.Size(257, 20);
            this.TextBoxsearch.TabIndex = 6;
            // 
            // EasyGrid1
            // 
            this.EasyGrid1.AutoGenerateColumns = false;
            this.EasyGrid1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.EasyGrid1.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
                        this.DataGridViewTextBoxColumn1,
                        this.DataGridViewTextBoxColumn2,
                        this.DataGridViewTextBoxColumn3,
                        this.DataGridViewTextBoxColumn4,
                        this.DataGridViewTextBoxColumn5,
                        this.DataGridViewTextBoxColumn6,
                        this.DataGridViewTextBoxColumn7,
                        this.DataGridViewTextBoxColumn8,
                        this.DataGridViewTextBoxColumn9,
                        this.DataGridViewTextBoxColumn10});
            this.EasyGrid1.ConnectionID = new System.Guid("50dc8941-d656-4888-9c35-65ce28a08610");
            this.EasyGrid1.DataPreparer = null;
            this.EasyGrid1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.EasyGrid1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.EasyGrid1.Field_DataSize = new int[] {
                    8,
                    4,
                    255,
                    255,
                    255,
                    255,
                    255,
                    4,
                    8,
                    8};
            this.EasyGrid1.Field_Editor = null;
            this.EasyGrid1.Field_Expression = new string[] {
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""};
            this.EasyGrid1.Field_FieldCaption = new string[] {
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null};
            this.EasyGrid1.Field_FieldText = new string[] {
                    "[GLASS].[date]",
                    "[GLASS].[USERiD]",
                    "[GLASS].[FIRST NAME]",
                    "[GLASS].[STATE]",
                    "[GLASS].[CONTACT NO]",
                    "[GLASS].[glass_type]",
                    "[GLASS].[task_type]",
                    "[GLASS].[dimension]",
                    "[GLASS].[f_charge]",
                    "[GLASS].[l_charge]"};
            this.EasyGrid1.Field_FromTableName = new string[] {
                    "GLASS",
                    "GLASS",
                    "GLASS",
                    "GLASS",
                    "GLASS",
                    "GLASS",
                    "GLASS",
                    "GLASS",
                    "GLASS",
                    "GLASS"};
            this.EasyGrid1.Field_Indexed = new bool[] {
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false};
            this.EasyGrid1.Field_Iscalculated = new bool[] {
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false};
            this.EasyGrid1.Field_IsIdentity = new bool[] {
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false};
            this.EasyGrid1.Field_Name = new string[] {
                    "date",
                    "USERiD",
                    "FIRST NAME",
                    "STATE",
                    "CONTACT NO",
                    "glass_type",
                    "task_type",
                    "dimension",
                    "f_charge",
                    "l_charge"};
            this.EasyGrid1.Field_OleDbType = new System.Data.OleDb.OleDbType[] {
                    System.Data.OleDb.OleDbType.DBDate,
                    System.Data.OleDb.OleDbType.Integer,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.VarWChar,
                    System.Data.OleDb.OleDbType.Integer,
                    System.Data.OleDb.OleDbType.Double,
                    System.Data.OleDb.OleDbType.Double};
            this.EasyGrid1.Field_ReadOnly = new bool[] {
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false};
            this.EasyGrid1.From = "[GLASS]";
            this.EasyGrid1.GroupBy = null;
            this.EasyGrid1.Having = null;
            this.EasyGrid1.Limit = null;
            this.EasyGrid1.Location = new System.Drawing.Point(78, 443);
            this.EasyGrid1.Name = "EasyGrid1";
            this.EasyGrid1.OrderBy = null;
            this.EasyGrid1.Param_Name = new string[0];
            this.EasyGrid1.Param_OleDbType = new System.Data.OleDb.OleDbType[0];
            this.EasyGrid1.Param_Value = new string[0];
            this.EasyGrid1.RowIndex = -1;
            this.EasyGrid1.Size = new System.Drawing.Size(1041, 155);
            this.EasyGrid1.SqlTop = 0;
            this.EasyGrid1.TabIndex = 7;
            this.EasyGrid1.TableName = "Table2685085478";
            this.EasyGrid1.TableToUpdate = "GLASS";
            this.EasyGrid1.Where = null;
            // 
            // DataGridViewTextBoxColumn1
            // 
            this.DataGridViewTextBoxColumn1.DataPropertyName = "date";
            this.DataGridViewTextBoxColumn1.HeaderText = "date";
            this.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1";
            // 
            // DataGridViewTextBoxColumn2
            // 
            this.DataGridViewTextBoxColumn2.DataPropertyName = "USERiD";
            this.DataGridViewTextBoxColumn2.HeaderText = "USERiD";
            this.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2";
            this.DataGridViewTextBoxColumn2.ReadOnly = true;
            // 
            // DataGridViewTextBoxColumn3
            // 
            this.DataGridViewTextBoxColumn3.DataPropertyName = "FIRST NAME";
            this.DataGridViewTextBoxColumn3.HeaderText = "FIRST NAME";
            this.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3";
            // 
            // DataGridViewTextBoxColumn4
            // 
            this.DataGridViewTextBoxColumn4.DataPropertyName = "STATE";
            this.DataGridViewTextBoxColumn4.HeaderText = "STATE";
            this.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4";
            // 
            // DataGridViewTextBoxColumn5
            // 
            this.DataGridViewTextBoxColumn5.DataPropertyName = "CONTACT NO";
            this.DataGridViewTextBoxColumn5.HeaderText = "CONTACT NO";
            this.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5";
            // 
            // DataGridViewTextBoxColumn6
            // 
            this.DataGridViewTextBoxColumn6.DataPropertyName = "glass_type";
            this.DataGridViewTextBoxColumn6.HeaderText = "glass_type";
            this.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6";
            // 
            // DataGridViewTextBoxColumn7
            // 
            this.DataGridViewTextBoxColumn7.DataPropertyName = "task_type";
            this.DataGridViewTextBoxColumn7.HeaderText = "task_type";
            this.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7";
            // 
            // DataGridViewTextBoxColumn8
            // 
            this.DataGridViewTextBoxColumn8.DataPropertyName = "dimension";
            this.DataGridViewTextBoxColumn8.HeaderText = "dimension";
            this.DataGridViewTextBoxColumn8.Name = "DataGridViewTextBoxColumn8";
            // 
            // DataGridViewTextBoxColumn9
            // 
            this.DataGridViewTextBoxColumn9.DataPropertyName = "f_charge";
            this.DataGridViewTextBoxColumn9.HeaderText = "f_charge";
            this.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9";
            // 
            // DataGridViewTextBoxColumn10
            // 
            this.DataGridViewTextBoxColumn10.DataPropertyName = "l_charge";
            this.DataGridViewTextBoxColumn10.HeaderText = "l_charge";
            this.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10";
            // 
            // Button2147483646
            // 
            this.Button2147483646.Location = new System.Drawing.Point(991, 618);
            this.Button2147483646.Name = "Button2147483646";
            this.Button2147483646.Size = new System.Drawing.Size(129, 23);
            this.Button2147483646.TabIndex = 8;
            this.Button2147483646.Text = "EXIT";
            this.Button2147483646.UseVisualStyleBackColor = true;
            this.Button2147483646.Click += new System.EventHandler(this.Click_a63a8416);
            // 
            // Buttonviewds
            // 
            this.Buttonviewds.Location = new System.Drawing.Point(80, 613);
            this.Buttonviewds.Name = "Buttonviewds";
            this.Buttonviewds.Size = new System.Drawing.Size(129, 23);
            this.Buttonviewds.TabIndex = 8;
            this.Buttonviewds.Text = "VIEW DATASET";
            this.Buttonviewds.UseVisualStyleBackColor = true;
            // 
            // Label12
            // 
            this.Label12.Location = new System.Drawing.Point(631, 618);
            this.Label12.Name = "Label12";
            this.Label12.Size = new System.Drawing.Size(100, 23);
            this.Label12.TabIndex = 9;
            this.Label12.Text = "MARK PENDING";
            // 
            // ComboBox3
            // 
            this.ComboBox3.FormattingEnabled = true;
            this.ComboBox3.Items.AddRange(new object[] {
                        "YES",
                        "NO"});
            this.ComboBox3.Location = new System.Drawing.Point(746, 618);
            this.ComboBox3.Name = "ComboBox3";
            this.ComboBox3.Size = new System.Drawing.Size(121, 21);
            this.ComboBox3.TabIndex = 10;
            this.ComboBox3.Text = "MARK";
            // 
            // Buttonnext
            // 
            this.Buttonnext.Location = new System.Drawing.Point(424, 613);
            this.Buttonnext.Name = "Buttonnext";
            this.Buttonnext.Size = new System.Drawing.Size(44, 23);
            this.Buttonnext.TabIndex = 8;
            this.Buttonnext.Text = "<<";
            this.Buttonnext.UseVisualStyleBackColor = true;
            // 
            // Buttonprevios
            // 
            this.Buttonprevios.Location = new System.Drawing.Point(485, 613);
            this.Buttonprevios.Name = "Buttonprevios";
            this.Buttonprevios.Size = new System.Drawing.Size(43, 23);
            this.Buttonprevios.TabIndex = 8;
            this.Buttonprevios.Text = ">>";
            this.Buttonprevios.UseVisualStyleBackColor = true;
            // 
            // Buttonpending
            // 
            this.Buttonpending.Location = new System.Drawing.Point(249, 613);
            this.Buttonpending.Name = "Buttonpending";
            this.Buttonpending.Size = new System.Drawing.Size(129, 23);
            this.Buttonpending.TabIndex = 8;
            this.Buttonpending.Text = "VIEW PENDING";
            this.Buttonpending.UseVisualStyleBackColor = true;
            // 
            // WebLoginManager1
            // 
            this.WebLoginManager1.ComponentName = "WebLoginManager1";
            this.WebLoginManager1.ConnectionID = new System.Guid("50dc8941-d656-4888-9c35-65ce28a08610");
            this.WebLoginManager1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.WebLoginManager1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.WebLoginManager1.FailedMessageLableId = null;
            this.WebLoginManager1.ID = new System.Guid("ccaad486-894b-47dd-ac52-66a07f34c979");
            this.WebLoginManager1.InactivityMinutes = 0;
            this.WebLoginManager1.LabelToShowLoginFailedMessage = null;
            this.WebLoginManager1.LoginFailedMessage = null;
            this.WebLoginManager1.LoginPermissionFailedMessage = null;
            this.WebLoginManager1.PasswordHash = WindowsUtility.EnumPasswordHash.SHA256;
            this.WebLoginManager1.UserAccountIdFieldName = "USERiD";
            this.WebLoginManager1.UserAccountLevelFieldName = "USER LEVEL";
            this.WebLoginManager1.UserAccountLoginFieldName = "LOGIN NAME";
            this.WebLoginManager1.UserAccountPasswordFieldName = "PASSWORD";
            this.WebLoginManager1.UserAccountResetCodeFieldName = "RESET CODE";
            this.WebLoginManager1.UserAccountResetCodeTimeFieldName = "RESET CODE EXPIRE";
            this.WebLoginManager1.UserAccountSaltFieldName = "SALT";
            this.WebLoginManager1.UserAccountTableName = "GLASS";
            // 
            // EasyDataSet1
            // 
            this.EasyDataSet1.ConnectionID = new System.Guid("50dc8941-d656-4888-9c35-65ce28a08610");
            this.EasyDataSet1.DataSetName = "Data_9ac99780-e619-4893-a6a2-77f1e6602619";
            this.EasyDataSet1.DefaultConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Users\\rishabh\\OneDrive\\Documents\\" +
                "SOFTWAREMERCHANT.mdb;Mode=ReadWrite;";
            this.EasyDataSet1.DefaultConnectionType = typeof(System.Data.OleDb.OleDbConnection);
            this.EasyDataSet1.Description = null;
            this.EasyDataSet1.DynamicParameters = dbparameterlistext1;
            this.EasyDataSet1.Field_DataSize = new int[0];
            this.EasyDataSet1.Field_FieldCaption = new string[0];
            this.EasyDataSet1.Field_FieldText = new string[0];
            this.EasyDataSet1.Field_FromTableName = new string[0];
            this.EasyDataSet1.Field_Indexed = new bool[0];
            this.EasyDataSet1.Field_IsIdentity = new bool[0];
            this.EasyDataSet1.Field_Name = new string[0];
            this.EasyDataSet1.Field_OleDbType = new System.Data.OleDb.OleDbType[0];
            this.EasyDataSet1.Field_ReadOnly = new bool[0];
            this.EasyDataSet1.From = null;
            this.EasyDataSet1.GroupBy = null;
            this.EasyDataSet1.Having = null;
            this.EasyDataSet1.IsFieldImage = new bool[0];
            this.EasyDataSet1.Limit = null;
            this.EasyDataSet1.Name = "EasyDataSet1";
            this.EasyDataSet1.OrderBy = null;
            this.EasyDataSet1.Param_Name = new string[0];
            this.EasyDataSet1.Param_OleDbType = new System.Data.OleDb.OleDbType[0];
            this.EasyDataSet1.Param_Value = new string[0];
            this.EasyDataSet1.TableName = "Table1158185324";
            this.EasyDataSet1.UpdatableTableName = null;
            this.EasyDataSet1.Where = null;
            // 
            // Form3
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(1184, 701);
            this.Controls.Add(this.LabelHEAD);
            this.Controls.Add(this.DateTimePicker1);
            this.Controls.Add(this.Label2);
            this.Controls.Add(this.GroupBox1);
            this.Controls.Add(this.GroupBox2);
            this.Controls.Add(this.Buttonsearch);
            this.Controls.Add(this.TextBoxsearch);
            this.Controls.Add(this.EasyGrid1);
            this.Controls.Add(this.Button2147483646);
            this.Controls.Add(this.Buttonviewds);
            this.Controls.Add(this.Label12);
            this.Controls.Add(this.ComboBox3);
            this.Controls.Add(this.Buttonnext);
            this.Controls.Add(this.Buttonprevios);
            this.Controls.Add(this.Buttonpending);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form3";
            this.Text = "Form3";
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox1.PerformLayout();
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox2.PerformLayout();
            EasyGrid1.CreateDataTable();
            EasyGrid1.Query();
            WebLoginManager1.CreateDataTable();
            EasyDataSet1.CreateDataTable();
            EasyDataSet1.Query();
            this.ComboBoxglasstype.DisplayMember = "glass_type";
            this.DateTimePicker1.DataBindings.Add(new System.Windows.Forms.Binding("Value", this.EasyGrid1.BindSource, "date", true));
            this.ComboBoxdimensions.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.EasyGrid1.BindSource, "dimension", true));
            this.ComboBoxglasstype.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.EasyGrid1.BindSource, "glass_type", true));
            this.TextBoxNM.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.EasyGrid1.BindSource, "FIRST NAME", true));
            this.TextBoxADD.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.EasyGrid1.BindSource, "STATE", true));
            this.TextBoxCONT.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.EasyGrid1.BindSource, "CONTACT NO", true));
            ((System.ComponentModel.ISupportInitialize)(EasyDataSet1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(EasyGrid1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_b7e1f75(object sender, System.EventArgs e)
        {
            this.ButtonCALC.Show();
        }
        private void Click_38f61cdd(object sender, System.EventArgs e)
        {
            string l390d8415;
            if ((this.TextBoxLCHR != null))
            {
                l390d8415 = this.TextBoxLCHR.ToString();
            }
            else
            {
                l390d8415 = string.Empty;
            }
            this.TextBoxLCHR.Text = l390d8415;
        }
        private void Click_a63a8416(object sender, System.EventArgs e)
        {
            return;
        }
        protected override void Dispose(bool disposing)
        {
            if ((disposing 
                        && (components != null)))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
